### ISSUE TITLE
`npm run start` returns `Cannot GET /` when visited

### ISSUE THREAD

**Issue by vidorteg** [webhintio/webhintio.github.io#1126]
After followng the README, it specifies to visit the address given by `npm run start` but the address returns a `Cannot Get/` error. The way I have been testing the site is spawing a server directly from `docs` so the right fix might be to deprecate this and spawn directly the server from `docs`

**Comment by MohitBansal321** [comment]
Hey can you provide more context on which repo are you getting this issue

**Comment by vidorteg** [comment]
fixed by #1219
