### ISSUE TITLE
Uh-oh! There's been an error and the scan could not start.

### ISSUE THREAD

**Issue by mass34** [webhintio/webhintio.github.io#930]
Bug report:
1. http://localhost:4000/scanner/
2. Linux  5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
3. Firefox79.0 (64-bit)
4. all websites
![4000](https://user-images.githubusercontent.com/18635003/89729398-fd8da480-da3d-11ea-9770-f30a11b7eec3.png)

**Comment by antross** [comment]
Thanks for the report @mass34! 

To clarify, are you trying to run the online scanner from your own machine? If so, can you share what you're trying to accomplish? Getting the configuration right to run the online scanner locally can be a bit tricky and we generally don't recommend it unless you're specifically trying to enhance/debug the scanner itself.

For most testing against live sites we recommend using either the production scanner hosted at https://webhint.io/scanner/, webhint's [CLI](https://webhint.io/docs/user-guide/), webhint's [browser extension](https://webhint.io/docs/user-guide/extensions/extension-browser/), or building on top of webhint's [Node API](https://webhint.io/docs/user-guide/api/using-api/).
